// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zajednica.Community.Infrastructure.Database;

#nullable disable

namespace Zajednica.Community.Infrastructure.Migrations
{
    [DbContext(typeof(CommunityDbContext))]
    [Migration("20260721011222_InitialCommunity")]
    partial class InitialCommunity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("community")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zajednica.Community.Core.Domain.BlacklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IntentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CommunityId")
                        .IsUnique();

                    b.ToTable("BlacklistEntries", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuerMembershipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("IssuerMembershipId", "CandidateMembershipId")
                        .IsUnique();

                    b.ToTable("Certificates", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.CertificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuerMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("CertificationChallenges", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("Communities", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PostedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Documents", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("AccountId", "CommunityId")
                        .IsUnique();

                    b.ToTable("Memberships", "community");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Community", b =>
                {
                    b.OwnsOne("Zajednica.Community.Core.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetName");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StreetNumber");

                            b1.HasKey("CommunityId");

                            b1.ToTable("Communities", "community");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");

                            b1.OwnsOne("Zajednica.Community.Core.Domain.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("AddressCommunityId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("Latitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("AddressCommunityId");

                                    b2.ToTable("Communities", "community");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressCommunityId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsOne("Zajednica.Community.Core.Domain.RegistrationNumber", "RegistrationNumber", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("RegistrationNumber");

                            b1.HasKey("CommunityId");

                            b1.ToTable("Communities", "community");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsOne("Zajednica.Community.Core.Domain.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("TaxId");

                            b1.HasKey("CommunityId");

                            b1.ToTable("Communities", "community");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("RegistrationNumber");

                    b.Navigation("TaxId");
                });

            modelBuilder.Entity("Zajednica.Community.Core.Domain.Membership", b =>
                {
                    b.OwnsMany("Zajednica.Community.Core.Domain.MembershipRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("GrantedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("GrantedByMembershipId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("MembershipId", "Role")
                                .IsUnique();

                            b1.ToTable("MembershipRoles", "community");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
