<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zajednica.Chat.Api\Zajednica.Chat.Api.csproj" />
    <ProjectReference Include="..\..\Community\Zajednica.Community.Api\Zajednica.Community.Api.csproj" />
    <ProjectReference Include="..\..\Feed\Zajednica.Feed.Api\Zajednica.Feed.Api.csproj" />
    <ProjectReference Include="..\..\Identity\Zajednica.Identity.Api\Zajednica.Identity.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
