// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zajednica.Feed.Infrastructure.Database;

#nullable disable

namespace Zajednica.Feed.Infrastructure.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    partial class FeedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("feed")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Intents.Events.IntentEvent", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("StreamId", "Sequence");

                    b.ToTable("IntentEvents", "feed");

                    b.HasDiscriminator<string>("Type").HasValue("IntentEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasReplies")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId", "ParentCommentId", "Date");

                    b.ToTable("Comments", "feed");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "DateCreated");

                    b.ToTable("Posts", "feed");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zajednica.Feed.Core.UseCases.Queries.IntentView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfClosure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EligibleVoterCount")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("QuorumReached")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesAgainst")
                        .HasColumnType("integer");

                    b.Property<bool>("VotesAreVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("VotesFor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Deadline")
                        .HasFilter("\"Status\" = 'Open'");

                    b.HasIndex("CommunityId", "DateCreated");

                    b.HasIndex("CommunityId", "TargetMembershipId")
                        .HasFilter("\"Status\" = 'Open'");

                    b.ToTable("IntentViews", "feed");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Intents.Events.IntentClosed", b =>
                {
                    b.HasBaseType("Zajednica.Feed.Core.Domain.Intents.Events.IntentEvent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("IntentClosed");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Intents.Events.UserTargetingIntentOpened", b =>
                {
                    b.HasBaseType("Zajednica.Feed.Core.Domain.Intents.Events.IntentEvent");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EligibleVoterCount")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetMembershipRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetMembershipStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("UserTargetingIntentOpened");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Intents.Events.VoteCast", b =>
                {
                    b.HasBaseType("Zajednica.Feed.Core.Domain.Intents.Events.IntentEvent");

                    b.Property<bool>("InFavor")
                        .HasColumnType("boolean");

                    b.Property<Guid>("VoterMembershipId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("VoteCast");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.GeneralTopicPost", b =>
                {
                    b.HasBaseType("Zajednica.Feed.Core.Domain.Posts.Post");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GeneralTopicPosts", "feed");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.HelpRequest", b =>
                {
                    b.HasBaseType("Zajednica.Feed.Core.Domain.Posts.Post");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.ToTable("HelpRequests", "feed");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.Comment", b =>
                {
                    b.HasOne("Zajednica.Feed.Core.Domain.Posts.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Zajednica.Feed.Core.Domain.Posts.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.Post", b =>
                {
                    b.OwnsMany("Zajednica.Feed.Core.Domain.Posts.Image", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.ToTable("Images", "feed");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.GeneralTopicPost", b =>
                {
                    b.HasOne("Zajednica.Feed.Core.Domain.Posts.Post", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Feed.Core.Domain.Posts.GeneralTopicPost", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.HelpRequest", b =>
                {
                    b.HasOne("Zajednica.Feed.Core.Domain.Posts.Post", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Feed.Core.Domain.Posts.HelpRequest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Feed.Core.Domain.Posts.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
