// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zajednica.Chat.Infrastructure.Database;

#nullable disable

namespace Zajednica.Chat.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260811112332_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chat")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "LastActivityAt");

                    b.ToTable("Chats", "chat");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.ChatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MembershipId");

                    b.ToTable("ChatParticipants", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderMembershipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Date");

                    b.ToTable("Messages", "chat");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.DirectChat", b =>
                {
                    b.HasBaseType("Zajednica.Chat.Core.Domain.Chat");

                    b.ToTable("DirectChats", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.HelpRequestChat", b =>
                {
                    b.HasBaseType("Zajednica.Chat.Core.Domain.Chat");

                    b.Property<int?>("AwardedStars")
                        .HasColumnType("integer");

                    b.Property<bool>("FirstResponse")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("HelpRequestId");

                    b.ToTable("HelpRequestChats", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.TemporaryChat", b =>
                {
                    b.HasBaseType("Zajednica.Chat.Core.Domain.Chat");

                    b.ToTable("TemporaryChats", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.TextMessage", b =>
                {
                    b.HasBaseType("Zajednica.Chat.Core.Domain.Message");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("TextMessages", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.VoiceMessage", b =>
                {
                    b.HasBaseType("Zajednica.Chat.Core.Domain.Message");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.ToTable("VoiceMessages", "chat");
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.ChatParticipant", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Chat", null)
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.Message", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.DirectChat", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Chat", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Chat.Core.Domain.DirectChat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.HelpRequestChat", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Chat", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Chat.Core.Domain.HelpRequestChat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.TemporaryChat", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Chat", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Chat.Core.Domain.TemporaryChat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.TextMessage", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Chat.Core.Domain.TextMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.VoiceMessage", b =>
                {
                    b.HasOne("Zajednica.Chat.Core.Domain.Message", null)
                        .WithOne()
                        .HasForeignKey("Zajednica.Chat.Core.Domain.VoiceMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zajednica.Chat.Core.Domain.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
